### ISSUE TITLE
RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!

### ISSUE THREAD

**Issue by harshad16** [thoth-station/si-bandit#25]
**Describe the bug**
si-bandit is running into dependency issue regarding the `urllib` package during the run time.
```
security-indicator-efba3f66-2946128251: Traceback (most recent call last):
security-indicator-efba3f66-2946128251:   File "/opt/app-root/lib/python3.6/site-packages/requests/__init__.py", line 55, in <module>
security-indicator-efba3f66-2946128251:     assert minor <= 22
security-indicator-efba3f66-2946128251: AssertionError
security-indicator-efba3f66-2946128251: 
security-indicator-efba3f66-2946128251: During handling of the above exception, another exception occurred:
security-indicator-efba3f66-2946128251: 
security-indicator-efba3f66-2946128251: Traceback (most recent call last):
security-indicator-efba3f66-2946128251:   File "app.py", line 29, in <module>
security-indicator-efba3f66-2946128251:     from thoth.analyzer import run_command
security-indicator-efba3f66-2946128251:   File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/__init__.py", line 3, in <module>
security-indicator-efba3f66-2946128251:     from .cli import print_command_result
security-indicator-efba3f66-2946128251:   File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/cli.py", line 31, in <module>
security-indicator-efba3f66-2946128251:     import requests
security-indicator-efba3f66-2946128251:   File "/opt/app-root/lib/python3.6/site-packages/requests/__init__.py", line 57, in <module>
security-indicator-efba3f66-2946128251:     raise RuntimeError('Requests dependency \'urllib3\' must be version >= 1.21.1, < 1.22!')
security-indicator-efba3f66-2946128251: RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!
```

**To Reproduce**
1. Execute `_OpenShift.schedule_security_indicator(python_package_name="click", python_package_version="0.2", python_package_index="https://pypi.org/simple", aggregation_function="process_data")`
2. See error

**Additional context**
The requests package has no constraint on urllib3 for the latest two releases. 
- requests v2.24.0 has urllib3 v1.25.8
- requests v2.23.0 has urllib3 v1.25.4

si-bandit dependencies: 
requests  v2.24.0
urllib3 v1.25.9

**Comment by harshad16** [comment]
The issue is resolved with the image v0.1.3 tag.

However, the issue was seen in the image, which was created in the cluster with the adviser result, maybe it should be inspected.

**Comment by fridex** [comment]
This is an interesting observation.

> **Additional context**
> The requests package has no constraint on urllib3 for the latest two releases.
> 
> * requests v2.24.0 has urllib3 v1.25.8
> * requests v2.23.0 has urllib3 v1.25.4
> 
> si-bandit dependencies:
> requests v2.24.0
> urllib3 v1.25.9

requests in version `requests<=2.24.0>=2.18.0` checks for `urllib3` and raises `RuntimeError` on import if the version is not the expected:

https://github.com/psf/requests/commit/d8e236780981f28228441029c689a5e8dccdd71b

Starting requests 2.22.0 the check and requirements were adjusted:

https://github.com/psf/requests/commit/aeda65bbe57ac5edbcc2d80db85d010befb7d419

My wild guess is that we installed a requests version `requests<=2.22.0>=2.18.0` and urllib3 in version `urllib3>=1.23`. Is that correct? It's not directly clear to me how it was fixed in the deployment though.

**Comment by goern** [comment]
@harshad16 is this still valid?

**Comment by harshad16** [comment]
cant verify, @KPostOffice  you have any insight on this.

**Comment by goern** [comment]
is this fixed?

**Comment by KPostOffice** [comment]
This is no longer observed, I think it's because we pinned down the `bandit` version :thinking:
